export const responsiveLaws = [
 "P0_P1_P2_MUST_REMAIN_DISCOVERABLE",
 "PATIENT_AND_HIGH_IMPACT_ACTION_REMAIN_ASSOCIATED",
 "CRITICAL_COUNT_MUST_NOT_DISAPPEAR",
 "COLLAPSED_CONTEXT_MUST_HAVE_DISCOVERABLE_ENTRY",
 "NO_HORIZONTAL_CLIPPING_OF_PRIMARY_ACTION",
 "NO_TOOLTIP_ONLY_CRITICAL_CONTENT",
 "ZOOM_200_REQUIRED",
 "C5_TARGETED_ZOOM_400"
] as const;
