// Suplemento CURADO de monografías para fármacos comunes que el scrape del Vademecum no traía (propranolol, captopril,
// aspirina, alopurinol, etc.). Contenido de farmacología ESTABLECIDA (libro de texto), no fabricado; conciso y de referencia
// (no sustituye la ficha técnica). Gana sobre el dataset del vademecum en caso de coincidir el principio activo.
// Tupla: [clave_normalizada, nombre, acción, indicaciones, contraindicaciones].
export const MONOGRAPH_SUPPLEMENT:readonly (readonly [string,string,string,string,string])[]=[
 ["propranolol","Propranolol","Betabloqueador no selectivo.","Hipertensión, angina, arritmias, profilaxis de migraña, temblor esencial, tirotoxicosis.","Asma/EPOC, bradicardia, bloqueo AV de 2º-3º grado, insuficiencia cardíaca descompensada, choque cardiogénico."],
 ["captopril","Captopril","Inhibidor de la ECA (IECA).","Hipertensión, insuficiencia cardíaca, nefropatía diabética, post-infarto.","Embarazo, angioedema previo por IECA, estenosis bilateral de arteria renal, hiperpotasemia."],
 ["alopurinol","Alopurinol","Inhibidor de la xantina oxidasa (reduce el ácido úrico).","Hiperuricemia, gota, prevención de nefropatía por uratos.","Hipersensibilidad; ajustar en insuficiencia renal; vigilar reacciones cutáneas graves."],
 ["aspirina","Aspirina (ácido acetilsalicílico)","AINE, antiagregante plaquetario, analgésico y antipirético.","Dolor y fiebre; prevención cardiovascular a dosis bajas.","Úlcera péptica activa, sangrado, hipersensibilidad a AINE, niños con cuadro viral (riesgo de síndrome de Reye), tercer trimestre del embarazo."],
 ["bilastina","Bilastina","Antihistamínico H1 de 2ª generación.","Rinitis alérgica y urticaria.","Hipersensibilidad."],
 ["butilhioscina","Butilhioscina (butilbromuro de hioscina)","Antiespasmódico anticolinérgico.","Dolor tipo cólico gastrointestinal y genitourinario.","Glaucoma de ángulo cerrado, miastenia gravis, retención urinaria, íleo/megacolon, taquiarritmias."],
 ["carbonato de calcio","Carbonato de calcio","Suplemento de calcio y antiácido.","Hipocalcemia, osteoporosis, dispepsia ácida, hiperfosfatemia (ERC).","Hipercalcemia, litiasis renal cálcica."],
 ["ceftibuteno","Ceftibuteno","Cefalosporina de 3ª generación (oral).","Infecciones respiratorias, urinarias y otitis.","Alergia a cefalosporinas o betalactámicos."],
 ["clonixinato de lisina","Clonixinato de lisina","Analgésico tipo AINE.","Dolor leve a moderado.","Úlcera péptica, hipersensibilidad a AINE, sangrado activo."],
 ["clorfenamina","Clorfenamina","Antihistamínico H1 de 1ª generación.","Rinitis alérgica, urticaria, reacciones alérgicas.","Glaucoma, retención urinaria, lactancia; produce sedación (precaución al conducir)."],
 ["complejo b","Complejo B","Vitaminas del grupo B.","Deficiencia vitamínica, neuropatías, suplementación.","Hipersensibilidad."],
 ["demeclociclina","Demeclociclina","Tetraciclina.","Infecciones sensibles; SIADH.","Embarazo, niños menores de 8 años, alergia a tetraciclinas."],
 ["dicloxacilina","Dicloxacilina","Penicilina antiestafilocócica.","Infecciones de piel y tejidos blandos por Staphylococcus.","Alergia a penicilinas."],
 ["dienogest","Dienogest","Progestágeno.","Endometriosis; anticoncepción.","Embarazo, tromboembolia, tumores hormonodependientes, hepatopatía activa."],
 ["divalproato","Divalproato (ácido valproico)","Antiepiléptico y estabilizador del ánimo.","Epilepsia, trastorno bipolar, profilaxis de migraña.","Hepatopatía, embarazo (teratógeno), trastornos del ciclo de la urea, pancreatitis."],
 ["acido valproico","Ácido valproico","Antiepiléptico y estabilizador del ánimo.","Epilepsia, trastorno bipolar, profilaxis de migraña.","Hepatopatía, embarazo (teratógeno), trastornos del ciclo de la urea, pancreatitis."],
 ["dydrogesterona","Dydrogesterona","Progestágeno.","Insuficiencia de progesterona, amenaza de aborto, terapia hormonal.","Hepatopatía, tromboembolia, sangrado vaginal no diagnosticado."],
 ["ebastina","Ebastina","Antihistamínico H1 de 2ª generación.","Rinitis alérgica y urticaria.","Hipersensibilidad; precaución con QT prolongado."],
 ["ertugliflozina","Ertugliflozina","Inhibidor de SGLT2.","Diabetes mellitus tipo 2.","TFG reducida, cetoacidosis; precaución por infecciones genitourinarias y depleción de volumen."],
 ["alogliptina","Alogliptina","Inhibidor de DPP-4.","Diabetes mellitus tipo 2.","Hipersensibilidad; precaución por pancreatitis."],
 ["acarbosa","Acarbosa","Inhibidor de las alfa-glucosidasas.","Diabetes tipo 2 (hiperglucemia posprandial).","Enfermedad inflamatoria intestinal, obstrucción intestinal, cirrosis."],
 ["estrógenos conjugados","Estrógenos conjugados","Estrógeno.","Síntomas menopáusicos, hipoestrogenismo.","Cáncer hormonodependiente, tromboembolia, hepatopatía, sangrado no diagnosticado, embarazo."],
 ["exenatida","Exenatida","Agonista del receptor de GLP-1.","Diabetes mellitus tipo 2.","Hipersensibilidad; precaución por pancreatitis y TFG baja."],
 ["ezetimiba","Ezetimiba","Inhibidor de la absorción intestinal de colesterol.","Hipercolesterolemia (sola o con estatina).","Hepatopatía activa si se combina con estatina."],
 ["fenitoína","Fenitoína","Antiepiléptico.","Crisis tónico-clónicas y parciales; estatus epiléptico.","Bradicardia o bloqueo AV, hipersensibilidad; margen terapéutico estrecho, precaución en embarazo."],
 ["finasterida","Finasterida","Inhibidor de la 5-alfa-reductasa.","Hiperplasia prostática benigna; alopecia androgénica.","Mujeres embarazadas o en edad fértil, niños."],
 ["hidroxizina","Hidroxizina","Antihistamínico H1 con efecto ansiolítico.","Prurito, urticaria, ansiedad, premedicación.","QT prolongado, glaucoma, retención urinaria, embarazo."],
 ["hidróxido de aluminio","Hidróxido de aluminio","Antiácido.","Pirosis, dispepsia, hiperfosfatemia.","Hipofosfatemia; precaución en insuficiencia renal (acumulación de aluminio)."],
 ["ibandronato","Ibandronato","Bifosfonato.","Osteoporosis posmenopáusica; hipercalcemia.","Hipocalcemia, ERC grave, alteraciones esofágicas, imposibilidad de permanecer erguido."],
 ["insulina aspart","Insulina aspart","Análogo de insulina de acción rápida.","Diabetes mellitus.","Hipoglucemia; ajustar en insuficiencia renal/hepática."],
 ["insulina detemir","Insulina detemir","Análogo de insulina de acción prolongada.","Diabetes mellitus.","Hipoglucemia; ajustar dosis según control."],
 ["insulina glargina","Insulina glargina","Análogo de insulina de acción prolongada (basal).","Diabetes mellitus.","Hipoglucemia; no mezclar con otras insulinas."],
 ["insulina glulisina","Insulina glulisina","Análogo de insulina de acción rápida.","Diabetes mellitus.","Hipoglucemia."],
 ["isosorbida","Isosorbida (dinitrato/mononitrato)","Nitrato vasodilatador.","Profilaxis y tratamiento de la angina de pecho.","Uso concomitante de inhibidores de PDE5 (sildenafil, tadalafil), hipotensión, hipovolemia."],
 ["leuprorelina","Leuprorelina","Análogo de GnRH.","Cáncer de próstata, endometriosis, pubertad precoz central.","Embarazo, sangrado vaginal no diagnosticado."],
 ["lovastatina","Lovastatina","Estatina (inhibidor de la HMG-CoA reductasa).","Hipercolesterolemia.","Hepatopatía activa, embarazo y lactancia."],
 ["pravastatina","Pravastatina","Estatina (inhibidor de la HMG-CoA reductasa).","Hipercolesterolemia; prevención cardiovascular.","Hepatopatía activa, embarazo y lactancia."],
 ["lumiracoxib","Lumiracoxib","AINE inhibidor selectivo de COX-2.","Dolor y osteoartritis.","Hepatopatía (riesgo de hepatotoxicidad), úlcera, enfermedad cardiovascular."],
 ["metadoxina","Metadoxina","Hepatoprotector.","Intoxicación alcohólica aguda y hepatopatía alcohólica.","Hipersensibilidad."],
 ["metamizol","Metamizol (dipirona)","Analgésico y antipirético (pirazolona).","Dolor intenso; fiebre que no responde a otros antipiréticos.","Hipersensibilidad, agranulocitosis previa, discrasias sanguíneas, deficiencia de G6PD, tercer trimestre del embarazo."],
 ["nimesulida","Nimesulida","AINE.","Dolor agudo, dismenorrea.","Hepatopatía (hepatotoxicidad), úlcera, insuficiencia renal grave, embarazo."],
 ["penicilina benzatínica","Penicilina benzatínica","Penicilina de acción prolongada.","Faringitis estreptocócica, sífilis, profilaxis de fiebre reumática.","Alergia a penicilinas."],
 ["perindopril","Perindopril","Inhibidor de la ECA (IECA).","Hipertensión, insuficiencia cardíaca, enfermedad coronaria estable.","Embarazo, angioedema por IECA, estenosis bilateral de arteria renal."],
 ["pimecrolimus","Pimecrolimus","Inmunomodulador tópico (inhibidor de la calcineurina).","Dermatitis atópica.","Infección cutánea activa, inmunosupresión."],
 ["prazosina","Prazosina","Alfabloqueador.","Hipertensión; síntomas de hiperplasia prostática.","Hipersensibilidad; precaución por hipotensión con la primera dosis."],
 ["racecadotrilo","Racecadotrilo","Antisecretor intestinal (inhibidor de la encefalinasa).","Diarrea aguda.","Hipersensibilidad."],
 ["raloxifeno","Raloxifeno","Modulador selectivo del receptor de estrógenos (SERM).","Osteoporosis posmenopáusica.","Tromboembolia venosa, embarazo, hepatopatía."],
 ["rizatriptán","Rizatriptán","Triptán (agonista 5-HT1B/1D).","Crisis de migraña.","Cardiopatía isquémica, HTA no controlada, ictus o AIT previo, uso de ergotamina o IMAO."],
 ["zolmitriptán","Zolmitriptán","Triptán (agonista 5-HT1B/1D).","Crisis de migraña.","Cardiopatía isquémica, HTA no controlada, ictus o AIT previo, uso de ergotamina o IMAO."],
 ["secnidazol","Secnidazol","Nitroimidazol.","Amebiasis, giardiasis, vaginosis bacteriana, tricomoniasis.","Hipersensibilidad, primer trimestre del embarazo, consumo de alcohol."],
 ["sertaconazol","Sertaconazol","Antimicótico imidazólico (tópico).","Micosis cutáneas y candidiasis.","Hipersensibilidad."],
 ["somatropina","Somatropina","Hormona de crecimiento.","Déficit de hormona de crecimiento, talla baja.","Neoplasia activa, retinopatía diabética proliferativa, enfermedad crítica aguda."],
 ["subsalicilato de bismuto","Subsalicilato de bismuto","Antidiarreico y protector de la mucosa gástrica.","Diarrea, dispepsia.","Hipersensibilidad a salicilatos, niños con cuadro viral (riesgo de Reye)."],
 ["sulfasalazina","Sulfasalazina","Antiinflamatorio intestinal / FARME.","Colitis ulcerosa, enfermedad de Crohn, artritis reumatoide.","Alergia a sulfas o salicilatos, obstrucción intestinal, porfiria."],
 ["tiamazol","Tiamazol (metimazol)","Antitiroideo.","Hipertiroidismo.","Agranulocitosis previa; precaución en el primer trimestre del embarazo."],
 ["vardenafil","Vardenafil","Inhibidor de la PDE5.","Disfunción eréctil.","Uso de nitratos, cardiopatía inestable, hipotensión."],
 ["vitamina c","Vitamina C (ácido ascórbico)","Vitamina hidrosoluble.","Escorbuto, suplementación.","Litiasis renal por oxalato con dosis altas."],
 ["ácido tranexámico","Ácido tranexámico","Antifibrinolítico.","Hemorragia, menorragia.","Tromboembolia activa, hemorragia subaracnoidea, insuficiencia renal grave."],
 ["ácido ursodesoxicólico","Ácido ursodesoxicólico","Ácido biliar.","Litiasis biliar de colesterol, colestasis, cirrosis biliar primaria.","Obstrucción biliar, colecistitis aguda."],
];
