"use client";
// GENERADO por scripts/refactor/split-workspace.mts (K-09): vista "biblioteca" del workspace, extraída de page.tsx sin cambios
// en su JSX ni en su lógica. Toma del contexto solo lo que usa.

import{card,LINE,P,UI,act}from"../shared";
import{useWorkspace}from"../context";
export default function BibliotecaView(){
 const{setView,setMedTab,setBibTab,bibTab,bibEsp,setBibEsp}=useWorkspace();

   // ===== MÓDULO BIBLIOTECA CLÍNICA (S-BIBLIOTECA) — repositorio de conocimiento curado (referencia) =====
   // Contenido de referencia (guías GPC, protocolos, artículos, fuentes externas): presentacional. Las herramientas
   // enlazadas que SÍ son deterministas y reales: Interacciones (verificador cableado), calculadoras (eGFR/IMC/CHA2DS2-VASc/NEWS2).
   const card2:React.CSSProperties={...card,marginTop:0};
   const selSty:React.CSSProperties={border:`1px solid ${LINE}`,borderRadius:9,padding:"8px 11px",fontSize:13,background:P.white,fontFamily:UI,color:P.ink};
   const BIB_TABS=["Todo","Guías (GPC)","Protocolos","Calculadoras","Escalas","Artículos","Medicamentos","Videos","Infografías","Plantillas"];
   const ESP:[string,string,number,string][]=[["Medicina general","M12 3a4 4 0 00-4 4c0 3 4 6 4 6s4-3 4-6a4 4 0 00-4-4z",245,P.purple],["Pediatría","M9 8a3 3 0 106 0 3 3 0 00-6 0zM6 21v-2a4 4 0 014-4h4a4 4 0 014 4v2",180,P.blue],["Ginecología","M12 3a4 4 0 100 8 4 4 0 000-8zM12 11v9M9 17h6",120,P.red],["Medicina interna","M12 21C12 21 4 13.5 4 8.5A4 4 0 0112 6a4 4 0 018 2.5C20 13.5 12 21 12 21z",210,P.red],["Urgencias","M12 5v14M5 12h14",95,P.red],["Dermatología","M4 4h16v16H4zM8 8h8v8H8z",80,P.amber],["Psiquiatría","M9 3a3 3 0 00-3 6 3 3 0 001 5 3 3 0 004 2 3 3 0 006 0 3 3 0 004-2 3 3 0 001-5 3 3 0 00-3-6",75,P.purple],["Nutrición","M12 3a5 5 0 015 5c0 4-5 13-5 13S7 12 7 8a5 5 0 015-5z",60,"#16A66A"],["Todas","M4 4h7v7H4zM13 4h7v7h-7zM4 13h7v7H4zM13 13h7v7h-7z",1250,P.muted]];
   type Feat={badge:string;bc:string;title:string;sub:string;desc:string;src:string;action:string;fav:boolean};
   const FEAT:Feat[]=[
    {badge:"GPC",bc:P.purple,title:"Diabetes mellitus tipo 2",sub:"GPC México 2024",desc:"Diagnóstico, tratamiento y seguimiento del paciente con DM2.",src:"CENETEC | 2024",action:"⤓ Descargar",fav:true},
    {badge:"Protocolo",bc:P.blue,title:"Manejo de la hipertensión arterial",sub:"GPC México 2023",desc:"Abordaje integral y metas de control.",src:"CENETEC | 2023",action:"⤓ Descargar",fav:false},
    {badge:"Calculadora",bc:"#16A66A",title:"Dosis pediátricas",sub:"Calculadora interactiva",desc:"Cálculo de dosis por peso, edad y medicamento.",src:"Medical OS | 2026",action:"▦ Abrir",fav:false},
    {badge:"Escala",bc:P.red,title:"Escala de Glasgow",sub:"Valoración neurológica",desc:"Evaluación del estado de conciencia en adultos y pediátricos.",src:"GPC Internacional | 2023",action:"⊟ Ver",fav:false},
   ];
   const badgeSty=(c:string):React.CSSProperties=>({background:c+"22",color:c,borderRadius:8,padding:"3px 10px",fontSize:11.5,fontWeight:700});
   const FAV=[["Antibióticos en IVU no complicada","GPC México 2024",P.blue],["Vacunación en el adulto","Esquema actualizado 2024",P.red],["Interpretación de EKG","Guía práctica",P.purple],["Dosis pediátricas","Calculadora","#16A66A"],["Manejo de asma","GPC México 2023",P.blue]];
   const REC=[["Colecistitis aguda","Protocolo | hace 2 horas",P.blue],["Insuficiencia renal aguda","GPC | hace 5 horas",P.red],["Anticonceptivos hormonales","Guía | hace 1 día","#16A66A"],["Crisis de ansiedad","Protocolo | hace 2 días",P.purple],["Interpretación de laboratorios","Guía | hace 3 días",P.blue]];
   const UPD=[["GPC Obesidad 2024","Hace 1 semana"],["Calendario de vacunación 2024","Hace 2 semanas"],["Manejo de dengue","Hace 3 semanas"]];
   const SRC:[string,string][]=[["CENETEC","México"],["OMS","Internacional"],["PubMed","Artículos"],["AHA","Cardiología"],["ADA","Diabetes"]];
   const listItem=(t:string,s:string,c:string,i:number,last:number)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"9px 0",borderBottom:i<last?`1px solid #F2F4F9`:"0"}}><span style={{width:26,height:26,borderRadius:7,background:c+"22",color:c,display:"grid",placeItems:"center",flex:"0 0 auto"}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M6 2h9l5 5v15H6z"/></svg></span><div style={{flex:1,minWidth:0}}><div style={{fontSize:12.5,fontWeight:700,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{t}</div><div style={{fontSize:11,color:P.muted}}>{s}</div></div><span style={{color:P.muted,fontWeight:700,cursor:"pointer"}}>⋯</span></div>;
   return <div style={{padding:"18px 24px 40px"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:12}}>
     <div style={{display:"flex",alignItems:"flex-start",gap:14}}><span style={{width:46,height:46,borderRadius:12,background:"#EEEBFD",color:P.purple,display:"grid",placeItems:"center",flex:"0 0 auto"}}><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden><path d="M4 5a2 2 0 012-2h6v18H6a2 2 0 01-2-2zM20 5a2 2 0 00-2-2h-6v18h6a2 2 0 002-2z"/></svg></span><div><h1 style={{fontSize:28,fontWeight:800,margin:0,letterSpacing:"-.02em"}}>Biblioteca Clínica</h1><p style={{color:P.muted,fontSize:13.5,margin:"4px 0 0"}}>Guías, protocolos, calculadoras, escalas y recursos médicos en un solo lugar.</p></div></div>
     <div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={()=>{setView("medicamentos");setMedTab("interacciones");}} style={{border:0,background:P.purple,color:"#fff",borderRadius:10,padding:"10px 18px",fontWeight:700,fontSize:13.5,cursor:"pointer",fontFamily:UI}}>Verificador de interacciones →</button></div>
    </div>
    <div style={{...card2,marginTop:14,padding:"12px 16px",background:"#FDF4E6",border:"1px solid #F2E1C0",fontSize:12.5,color:"#7A5A16",lineHeight:1.5}}>Catálogo de referencia (presentacional). Los nombres de guías y fuentes son reales, pero la <b>descarga, subida y búsqueda de documentos</b> se conectarán con el repositorio de contenido (aún no implementado). Las herramientas <b>operativas y deterministas</b> son el <b>verificador de interacciones</b> y las <b>calculadoras del motor CDS</b>.</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:12,marginTop:16}} className="mos-kpis">
     {([["#EEEBFD",P.purple,"M4 5a2 2 0 012-2h12v18H6a2 2 0 01-2-2z","Guías y protocolos","Nacionales e internacionales"],["#E6F6EE","#16A66A","M4 4h16v16H4zM8 8h8M8 12h8M8 16h4","Calculadoras médicas","Dosis, escalas (motor CDS)"],["#E7EEFB",P.blue,"M9 3h6l1 4H8zM7 7h10l1 13H6z","Artículos científicos","Fuentes externas (PubMed)"],["#FBF0DC",P.amber,"M12 3a9 9 0 100 18 9 9 0 000-18zM10 8l6 4-6 4z","Recursos educativos","Vídeos, infografías y casos"]] as [string,string,string,string,string][]).map(([bg,fg,d,l,s])=><div key={l} style={{...card2,padding:16,display:"flex",gap:13,alignItems:"center"}}><span style={{width:44,height:44,borderRadius:12,background:bg,display:"grid",placeItems:"center",flex:"0 0 auto"}}><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke={fg} strokeWidth="1.8"><path d={d}/></svg></span><div><div style={{fontSize:13.5,fontWeight:800}}>{l}</div><div style={{fontSize:11,color:P.muted}}>{s}</div></div></div>)}
    </div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 300px",gap:16,marginTop:16,alignItems:"start"}} className="mos-bib">
     <div style={{display:"flex",flexDirection:"column",gap:16}}>
      <div style={{...card2,padding:16}}>
       <div style={{display:"flex",gap:4,borderBottom:`1px solid ${LINE}`,overflowX:"auto",marginBottom:14}}>{BIB_TABS.map(t=><button key={t} onClick={()=>setBibTab(t)} style={{padding:"10px 11px",fontSize:13,fontWeight:bibTab===t?700:500,color:bibTab===t?P.purple:P.muted,borderBottom:bibTab===t?`2px solid ${P.purple}`:"2px solid transparent",background:"transparent",border:0,borderBottomWidth:2,cursor:"pointer",fontFamily:UI,whiteSpace:"nowrap"}}>{t}</button>)}</div>
       <div style={{fontSize:16,fontWeight:800,margin:"4px 0 10px"}}>Especialidades</div>
       <div style={{display:"grid",gridTemplateColumns:"repeat(9,1fr)",gap:8}}>{ESP.map(([l,d,n,c])=>{const on=l===bibEsp;return <div key={l} {...act(()=>setBibEsp(l))} style={{border:on?`1.5px solid ${P.purple}`:`1px solid ${LINE}`,borderRadius:11,padding:"12px 4px",display:"flex",flexDirection:"column",alignItems:"center",gap:6,cursor:"pointer",background:on?"#F7F6FE":P.white}}><span style={{color:c as string}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d={d as string}/></svg></span><span style={{fontSize:10.5,fontWeight:700,textAlign:"center",lineHeight:1.1}}>{l}</span></div>;})}</div>
       <div style={{fontSize:16,fontWeight:800,margin:"18px 0 10px"}}>Contenido destacado <span style={{fontSize:12,fontWeight:500,color:P.muted}}>(referencia)</span></div>
       <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{FEAT.map((f,i)=><div key={i} style={{border:`1px solid ${LINE}`,borderRadius:12,padding:14,display:"flex",flexDirection:"column"}}><span style={badgeSty(f.bc)}>{f.badge}</span><div style={{fontSize:14.5,fontWeight:700,marginTop:10,lineHeight:1.2}}>{f.title}</div><div style={{fontSize:11.5,color:P.muted,marginTop:2}}>{f.sub}</div><div style={{fontSize:12,color:"#4B5168",marginTop:8,lineHeight:1.4,flex:1,minHeight:48}}>{f.desc}</div><div style={{fontSize:11,color:P.muted,marginTop:8}}>{f.src}</div></div>)}</div>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,alignItems:"start"}} className="mos-bib2">
       <div style={{...card2,padding:16}}><div style={{fontSize:15,fontWeight:800,marginBottom:12}}>Herramientas rápidas</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{([["Verificador de interacciones","Motor determinista (real)",P.purple,()=>{setView("medicamentos");setMedTab("interacciones");}],["IMC y signos vitales","Cálculo al capturar en el módulo",P.amber,()=>setView("signos")]] as [string,string,string,()=>void][]).map(([t,s,c,fn],i)=><div key={i} {...act(fn)} style={{border:`1px solid ${LINE}`,borderRadius:11,padding:12,display:"flex",gap:10,alignItems:"center",cursor:"pointer"}}><span style={{width:34,height:34,borderRadius:9,background:(c as string)+"22",color:c as string,display:"grid",placeItems:"center",flex:"0 0 auto"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 4h16v16H4zM8 8h8"/></svg></span><div><div style={{fontSize:12.5,fontWeight:700}}>{t}</div><div style={{fontSize:11,color:P.muted}}>{s}</div></div></div>)}</div></div>
       <div style={{...card2,padding:16}}><div style={{fontSize:15,fontWeight:800,marginBottom:12}}>Fuentes confiables</div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{SRC.map(([n,s],i)=><div key={i} style={{flex:"1 0 80px",border:`1px solid ${LINE}`,borderRadius:11,padding:"12px 6px",display:"flex",flexDirection:"column",alignItems:"center",gap:5,textAlign:"center"}}><span style={{width:32,height:32,borderRadius:"50%",background:"#EEEBFD",color:P.purple,display:"grid",placeItems:"center",fontSize:11,fontWeight:800}}>{n.slice(0,2)}</span><span style={{fontSize:11.5,fontWeight:700}}>{n}</span><span style={{fontSize:10,color:P.muted}}>{s}</span></div>)}<div style={{flex:"1 0 80px",border:`1px solid ${LINE}`,borderRadius:11,display:"grid",placeItems:"center",color:P.muted}}>⋯</div></div></div>
      </div>
     </div>
     {/* Columna derecha */}
     <div style={{display:"flex",flexDirection:"column",gap:16}}>
      <div style={{...card2,padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:15,fontWeight:800,display:"flex",alignItems:"center",gap:8}}><span style={{color:P.amber}}>★</span>Mis favoritos</div><span style={{fontSize:12,color:P.blue,cursor:"pointer"}}>Ver todos</span></div>{FAV.map(([t,s,c],i)=>listItem(t as string,s as string,c as string,i,FAV.length-1))}</div>
      <div style={{...card2,padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:15,fontWeight:800,display:"flex",alignItems:"center",gap:8}}>◔ Recientes</div><span style={{fontSize:12,color:P.blue,cursor:"pointer"}}>Ver todos</span></div>{REC.map(([t,s,c],i)=>listItem(t as string,s as string,c as string,i,REC.length-1))}</div>
      <div style={{...card2,padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><div style={{fontSize:15,fontWeight:800,display:"flex",alignItems:"center",gap:8}}>🔔 Actualizaciones</div><span style={{fontSize:12,color:P.blue,cursor:"pointer"}}>Ver todos</span></div>{UPD.map(([t,s],i)=><div key={i} style={{display:"flex",gap:9,alignItems:"center",padding:"8px 0",borderBottom:i<UPD.length-1?`1px solid #F2F4F9`:"0"}}><span style={{background:"#E6F6EE",color:P.green,borderRadius:6,padding:"2px 8px",fontSize:10.5,fontWeight:700}}>Nuevo</span><div style={{flex:1}}><div style={{fontSize:12.5,fontWeight:700}}>{t}</div><div style={{fontSize:11,color:P.muted}}>{s}</div></div></div>)}</div>
     </div>
    </div>
    <div style={{...card2,marginTop:16,padding:"20px 24px",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:16,background:"linear-gradient(90deg,#F3F0FF,#EEF4FF)"}}>
     <div style={{display:"flex",alignItems:"center",gap:16}}><span style={{fontSize:34}}>📖</span><div><div style={{fontSize:18,fontWeight:800,color:P.purple}}>Conocimiento que mejora vidas</div><div style={{fontSize:13,color:P.muted,marginTop:2}}>Accede a la mejor evidencia científica, siempre actualizada, integrada en tu práctica clínica.</div></div></div>
     <div style={{display:"flex",alignItems:"center",gap:20,flexWrap:"wrap"}}><div style={{fontSize:12.5,color:P.muted,fontStyle:"italic",maxWidth:280}}>"La buena medicina se basa en el mejor conocimiento disponible."</div></div>
    </div>
   </div>;
  
}
