"use client";
// GENERADO por scripts/refactor/split-workspace.mts (K-09): vista "resultados" del workspace, extraída de page.tsx sin cambios
// en su JSX ni en su lógica. Toma del contexto solo lo que usa.
import {labReferenceRanges,acceptedUnitsOf,canonicalUnitOf} from "../../../../../packages/lab-reference/src";
import{card,P,LINE,UI,scrollToSection,act,Skeleton}from"../shared";
import{useWorkspace}from"../context";
export default function ResultadosView(){
 const{resReg,resQ,resTypeF,resEstadoF,resSel,setResNew,setResMsg2,resNew,setView,setResTab,resTab,resMsg2,resForm,setResForm,patientList,createResult,resBusy2,setResSel,setResQ,setResTypeF,setResEstadoF,ordReg}=useWorkspace();

   // ===== MÓDULO RESULTADOS — S7 (5 pestañas) =====
   const card2:React.CSSProperties={...card,marginTop:0};
   const link:React.CSSProperties={color:P.blue,fontSize:12.5,fontWeight:600,cursor:"pointer"};
   const RTABS:[typeof resTab,string,string][]=[["resultados","Resultados","M9 3h6M10 3v6l-5 9a2 2 0 002 3h10a2 2 0 002-3l-5-9V3"],["solicitudes","Solicitudes","M7 3h10v18H7zM10 8h4M10 12h4"],["seguimiento","Panel de seguimiento","M4 5h16v16H4zM8 3v4M16 3v4"],["referencia","Valores de referencia","M9 3h6M10 3v6l-5 9a2 2 0 002 3h10a2 2 0 002-3l-5-9V3"],["alertas","Alertas","M6 9a6 6 0 1112 0c0 5 2 6 2 6H4s2-1 2-6"]];
   const kico=(bg:string,fg:string,d:string)=><span style={{width:40,height:40,borderRadius:11,background:bg,display:"grid",placeItems:"center",flex:"0 0 auto"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke={fg} strokeWidth="1.8" aria-hidden><path d={d}/></svg></span>;
   const kcard:React.CSSProperties={...card2,padding:15,display:"flex",gap:12,alignItems:"center"};
   const flbl:React.CSSProperties={fontSize:12,fontWeight:700,color:P.muted,margin:"14px 0 6px"};
   const selSty:React.CSSProperties={width:"100%",border:`1px solid ${LINE}`,borderRadius:9,padding:"9px 11px",fontSize:13,background:P.white,fontFamily:UI,color:P.ink};
   const rb=(s:string):[string,string]=>s==="Hallazgos"?["#FBEEDF",P.amberOnPale]:s==="En seguimiento"?["#EAF1FD",P.blueOnPale]:s==="En revisión"?["#FBF0DC",P.amberOnPale]:["#E6F6EE",P.greenOnPale];
   const resLoaded=!!resReg;
   const fmtResD=(iso:string)=>{if(!iso)return"—";const d=new Date(iso);return isNaN(d.getTime())?"—":d.toLocaleDateString("es-MX",{day:"2-digit",month:"short",year:"numeric"});};
   const allItems=resReg?.items??[];
   // Navegador de resultados: filtros REALES (búsqueda + tipo + estado) sobre los items del registro
   const filteredItems=allItems.filter(it=>{const q=resQ.trim().toLowerCase();const okQ=!q||it.analyte.toLowerCase().includes(q)||it.patientName.toLowerCase().includes(q);const okT=resTypeF==="Todos"||it.tipo===resTypeF;const okE=resEstadoF==="Todos"||it.estado===resEstadoF;return okQ&&okT&&okE;});
   const selItem=filteredItems.find(it=>it.resultId===resSel)??filteredItems[0]??null;
   const kTot=resReg?.total??0,kAbn=resReg?.abnormal??0,kSeg=resReg?.enSeguimiento??0,kPen=resReg?.pendientes??0;
   const ricoPath:Record<string,string>={flask:"M9 3h6M10 3v6l-5 9a2 2 0 002 3h10a2 2 0 002-3l-5-9V3",clip:"M9 4h6v2H9zM7 5H6v16h12V5h-1M8 11h8M8 15h6",img:"M3 5h18v14H3zM3 15l5-5 4 4 3-3 6 6"};
   const pill=(bg:string,fg:string,t:string)=><span style={{fontSize:10.5,fontWeight:700,borderRadius:999,padding:"2px 9px",background:bg,color:fg}}>{t}</span>;
   return <div style={{padding:"18px 24px 40px"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:12}}>
     <div style={{display:"flex",alignItems:"flex-start",gap:14}}><span style={{width:46,height:46,borderRadius:12,background:"#EEEBFD",color:P.purple,display:"grid",placeItems:"center",flex:"0 0 auto"}}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden><path d="M9 3h6M10 3v6l-5 9a2 2 0 002 3h10a2 2 0 002-3l-5-9V3"/></svg></span><div><h1 style={{fontSize:28,fontWeight:800,margin:0,letterSpacing:"-.02em"}}>Resultados</h1><p style={{color:P.muted,fontSize:13.5,margin:"4px 0 0"}}>Consulta, analiza y da seguimiento a estudios de laboratorio, imagenología y otros resultados.</p></div></div>
     <div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button style={{border:0,background:P.purple,color:"#fff",borderRadius:10,padding:"10px 16px",fontWeight:700,fontSize:13.5,cursor:"pointer",fontFamily:UI}} onClick={()=>{setResNew(v=>!v);setResMsg2(null);}}>{resNew?"Cerrar":"+ Registrar resultado"}</button><button style={{border:`1px solid ${LINE}`,background:P.white,borderRadius:10,padding:"10px 16px",fontWeight:600,fontSize:13.5,cursor:"pointer",fontFamily:UI}} onClick={()=>setView("ordenes")}>Solicitar estudio</button></div>
    </div>
    <div style={{display:"flex",gap:2,marginTop:14,borderBottom:`1px solid ${LINE}`,overflowX:"auto"}}>{RTABS.map(([k,l,d])=><button key={k} onClick={()=>setResTab(k)} style={{display:"flex",alignItems:"center",gap:8,padding:"12px 16px",fontSize:13.5,fontWeight:resTab===k?700:500,color:resTab===k?P.purple:P.muted,cursor:"pointer",borderBottom:resTab===k?`2px solid ${P.purple}`:"2px solid transparent",background:"transparent",border:0,borderBottomWidth:2,fontFamily:UI,whiteSpace:"nowrap"}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden><path d={d}/></svg>{l}</button>)}</div>
    {resMsg2&&<div style={{marginTop:14,display:"flex",alignItems:"center",gap:10,background:resMsg2.includes("CRÍTICO")?"#FDECEE":resMsg2.includes("✓")?"#F0FBF4":"#EEF6FF",border:`1px solid ${resMsg2.includes("CRÍTICO")?"#F3C9C9":resMsg2.includes("✓")?"#CDEBD8":"#CFE0F7"}`,borderRadius:10,padding:"10px 14px",fontSize:13}}><span style={{color:resMsg2.includes("CRÍTICO")?P.red:resMsg2.includes("✓")?P.green:P.blue,fontWeight:700}}>{resMsg2.includes("CRÍTICO")?"⚠":resMsg2.includes("✓")?"✓":"ℹ"}</span><span style={{flex:1}}>{resMsg2}</span><button onClick={()=>setResMsg2(null)} style={{border:0,background:"transparent",color:P.muted,cursor:"pointer",fontFamily:UI,fontSize:14}}>×</button></div>}
    {resNew&&<div style={{...card,marginTop:14,padding:18}}>
     <div style={{fontWeight:800,fontSize:16,marginBottom:4}}>Registrar resultado</div>
     <div style={{fontSize:12.5,color:P.muted,marginBottom:12}}>La interpretación (normal / crítico) la <b style={{color:P.ink}}>deriva el motor CDS</b> del valor; un crítico sin cerrar bloquea la firma.</div>
     <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 140px",gap:14}} className="mos-med2">
      <div><div style={{fontSize:12,fontWeight:700,color:P.muted,margin:"0 0 6px"}}>Paciente</div><select value={resForm.patientId} onChange={e=>setResForm({...resForm,patientId:e.target.value})} style={{width:"100%",border:`1px solid ${LINE}`,borderRadius:9,padding:"9px 11px",fontSize:13,background:P.white,fontFamily:UI,color:P.ink}}><option value="">Selecciona…</option>{(patientList??[]).map(p=><option key={p.patientId} value={p.patientId}>{p.name}</option>)}</select></div>
      <div><div style={{fontSize:12,fontWeight:700,color:P.muted,margin:"0 0 6px"}}>Analito</div><select value={resForm.analyte} onChange={e=>setResForm({...resForm,analyte:e.target.value,unit:canonicalUnitOf(e.target.value)??""})} style={{width:"100%",border:`1px solid ${LINE}`,borderRadius:9,padding:"9px 11px",fontSize:13,background:P.white,fontFamily:UI,color:P.ink}}>{labReferenceRanges().map(a=><option key={a.analyte} value={a.analyte}>{a.analyte}</option>)}</select></div>
      <div><div style={{fontSize:12,fontWeight:700,color:P.muted,margin:"0 0 6px"}}>Valor</div><div style={{display:"flex",gap:6}}><input aria-label="Valor del resultado" inputMode="decimal" value={resForm.value} onChange={e=>setResForm({...resForm,value:e.target.value})} placeholder="Ej. 95" style={{flex:"1 1 auto",minWidth:0,border:`1px solid ${LINE}`,borderRadius:9,padding:"9px 11px",fontSize:13,background:P.white,fontFamily:UI,color:P.ink}}/><select aria-label="Unidad del resultado" value={resForm.unit} onChange={e=>setResForm({...resForm,unit:e.target.value})} style={{flex:"0 0 auto",border:`1px solid ${LINE}`,borderRadius:9,padding:"9px 8px",fontSize:13,background:P.white,fontFamily:UI,color:P.ink}}>{acceptedUnitsOf(resForm.analyte).map(u=><option key={u} value={u}>{u}</option>)}</select></div></div>
     </div>
     {(()=>{const rng=labReferenceRanges().find(a=>a.analyte===resForm.analyte);return rng?<div style={{fontSize:11.5,color:P.muted,marginTop:8}}>Rango normal {resForm.analyte}: {rng.normalLow}–{rng.normalHigh}{rng.unit?` ${rng.unit}`:""}{rng.criticalLow!=null||rng.criticalHigh!=null?` · crítico <${rng.criticalLow??"—"} o >${rng.criticalHigh??"—"}`:""}{rng.stratum&&rng.stratum!=="adulto"?` · criterio: ${rng.stratum}`:""}</div>:null;})()}
     <div style={{display:"flex",gap:10,marginTop:16}}><button onClick={()=>void createResult()} disabled={resBusy2||!resForm.patientId||!resForm.value.trim()} style={{border:0,background:(resBusy2||!resForm.patientId||!resForm.value.trim())?"#C7CCE0":P.purple,color:"#fff",borderRadius:10,padding:"11px 20px",fontWeight:700,fontSize:14,cursor:(resBusy2||!resForm.patientId||!resForm.value.trim())?"default":"pointer",fontFamily:UI}}>{resBusy2?"Registrando…":"Registrar resultado"}</button><button onClick={()=>setResNew(false)} style={{border:`1px solid ${LINE}`,background:P.white,borderRadius:10,padding:"11px 18px",fontWeight:600,fontSize:14,cursor:"pointer",fontFamily:UI}}>Cancelar</button></div>
    </div>}
    <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:12,marginTop:16}} className="mos-kpis">
     <div style={kcard}>{kico("#EEEBFD",P.purple,"M4 4h16v16H4zM8 9h8M8 13h5")}<div>{resLoaded?<div style={{fontSize:22,fontWeight:800}}>{kTot}</div>:<Skeleton w={38} h={20} style={{margin:"2px 0"}}/>}<div style={{fontSize:11.5,color:P.muted}}>Resultados totales</div></div></div>
     <div style={kcard}>{kico("#FDECEE",P.red,"M9 3h6M10 3v6l-5 9a2 2 0 002 3h10a2 2 0 002-3l-5-9V3")}<div>{resLoaded?<div style={{fontSize:22,fontWeight:800}}>{kAbn}</div>:<Skeleton w={38} h={20} style={{margin:"2px 0"}}/>}<div style={{fontSize:11.5,color:P.muted}}>Con hallazgos anormales</div></div></div>
     <div style={kcard}>{kico("#FBF0DC",P.amber,"M12 8v4l3 2M21 12a9 9 0 11-18 0 9 9 0 0118 0")}<div>{resLoaded?<div style={{fontSize:22,fontWeight:800}}>{kSeg}</div>:<Skeleton w={38} h={20} style={{margin:"2px 0"}}/>}<div style={{fontSize:11.5,color:P.muted}}>En seguimiento</div></div></div>
     <div style={kcard}>{kico("#E7EEFB",P.blue,"M7 3h10v18H7zM10 8h4")}<div>{resLoaded?<div style={{fontSize:22,fontWeight:800}}>{kPen}</div>:<Skeleton w={38} h={20} style={{margin:"2px 0"}}/>}<div style={{fontSize:11.5,color:P.muted}}>Pendientes de revisión</div></div></div>
    </div>
    {resTab!=="resultados"?(
     (()=>{
      const th2:React.CSSProperties={textAlign:"left",fontSize:11.5,color:P.muted,fontWeight:600,padding:"11px 12px",borderBottom:`1px solid ${LINE}`,whiteSpace:"nowrap"};
      const td2:React.CSSProperties={padding:"10px 12px",borderBottom:`1px solid #F2F4F9`,fontSize:12.5,whiteSpace:"nowrap"};
      if(resTab==="alertas"){
       const rows=(resReg?.items??[]).filter(i=>i.estado==="Hallazgos"||i.critical);
       return <div style={{...card2,marginTop:16,padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div style={{fontSize:16,fontWeight:800}}>Alertas de resultados ({rows.length})</div><span style={{fontSize:12,color:P.muted}}>Valores críticos y hallazgos anormales (motor CDS determinista)</span></div>{rows.map((a,i)=><div key={a.resultId} style={{display:"flex",gap:11,alignItems:"center",padding:"12px 14px",borderRadius:11,background:"#FDECEE",border:"1px solid #F6C9D0",marginBottom:i<rows.length-1?10:0}}><span style={{color:P.red,flex:"0 0 auto"}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="12" cy="12" r="9"/><path d="M12 8v4M12 16h.01"/></svg></span><div style={{flex:1,minWidth:0}}><div style={{fontSize:13.5,fontWeight:700}}>{a.analyte} = {a.value} <span style={{color:"#9c1f34"}}>· {a.patientName}</span></div><div style={{fontSize:12,color:P.redOnPale}}>{a.interpretation||"Hallazgo anormal"}</div></div><button onClick={()=>{setResTab("resultados");setResSel(a.resultId);setResQ("");setResTypeF("Todos");setResEstadoF("Todos");}} style={{border:`1px solid ${P.red}`,background:P.white,color:P.red,borderRadius:8,padding:"6px 12px",fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:UI}}>Revisar</button></div>)}{rows.length===0&&<div style={{padding:"40px",textAlign:"center",color:P.muted}}>Sin alertas de resultados. Todos los valores están en rango.</div>}</div>;
      }
      if(resTab==="seguimiento"){
       const rows=(resReg?.items??[]).filter(i=>i.lifecycle==="ACTIONED");
       return <div style={{...card2,marginTop:16,padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:16,fontWeight:800}}>Panel de seguimiento ({rows.length})</div><span style={{fontSize:12,color:P.muted}}>Zero-Lost-Follow-Up: resultados con acción/obligación abierta</span></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={th2}>Estudio</th><th style={th2}>Valor</th><th style={th2}>Paciente</th><th style={th2}>Interpretación</th><th style={{...th2,textAlign:"right"}}>Estado</th></tr></thead><tbody>{rows.map(r=><tr key={r.resultId}><td style={{...td2,fontWeight:600}}>{r.analyte}</td><td style={td2}>{r.value}</td><td style={td2}>{r.patientName}</td><td style={{...td2,color:P.muted,whiteSpace:"normal"}}>{r.interpretation}</td><td style={{...td2,textAlign:"right"}}>{pill("#EAF1FD",P.blueOnPale,"En seguimiento")}</td></tr>)}{rows.length===0&&<tr><td colSpan={5} style={{...td2,textAlign:"center",color:P.muted,padding:"30px"}}>Sin resultados en seguimiento activo.</td></tr>}</tbody></table></div></div>;
      }
      if(resTab==="solicitudes"){
       const rows=(ordReg?.items??[]).slice(0,20).map(o=>({typeLabel:o.typeLabel,detail:o.detail,patientName:o.patientName,status:o.status,createdAt:fmtResD(o.createdAt)}));
       const totO=ordReg?.total??0;
       const est=(s:string):[string,string]=>s==="Completada"?["#E6F6EE",P.greenOnPale]:s==="Enviada"?["#EAF1FD",P.blueOnPale]:s==="Cancelada"?["#EEF1F7",P.muted]:["#FBF0DC",P.amberOnPale];
       return <div style={{...card2,marginTop:16,padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:16,fontWeight:800}}>Solicitudes de estudio ({totO})</div><button style={{border:`1px solid ${LINE}`,background:P.white,borderRadius:9,padding:"7px 12px",fontWeight:600,fontSize:12.5,cursor:"pointer",fontFamily:UI}} onClick={()=>{setView("exp");setTimeout(()=>scrollToSection("Órdenes clínicas"),0);}}>+ Nueva solicitud</button></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={th2}>Estudio</th><th style={th2}>Tipo</th><th style={th2}>Paciente</th><th style={th2}>Fecha</th><th style={{...th2,textAlign:"right"}}>Estado</th></tr></thead><tbody>{rows.map((r,i)=>{const[bg,fg]=est(r.status);return <tr key={i}><td style={{...td2,fontWeight:600}}>{r.detail}</td><td style={{...td2,color:P.muted}}>{r.typeLabel}</td><td style={td2}>{r.patientName}</td><td style={{...td2,color:P.muted}}>{r.createdAt}</td><td style={{...td2,textAlign:"right"}}>{pill(bg,fg,r.status)}</td></tr>;})}{rows.length===0&&<tr><td colSpan={5} style={{...td2,textAlign:"center",color:P.muted,padding:"30px"}}>Sin solicitudes de estudio.</td></tr>}</tbody></table></div></div>;
      }
      if(resTab==="referencia"){
       const ranges=labReferenceRanges();
       return <div style={{...card2,marginTop:16,padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:16,fontWeight:800}}>Valores de referencia ({ranges.length} analitos)</div><span style={{fontSize:12,color:P.muted}}>Rangos del motor CDS · los mismos con los que se clasifica cada resultado</span></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={th2}>Analito</th><th style={th2}>Unidad</th><th style={th2}>Rango normal</th><th style={th2}>Crítico bajo</th><th style={th2}>Crítico alto</th><th style={th2}>Estrato</th><th style={th2}>Fuente</th></tr></thead><tbody>{ranges.map((r,i)=><tr key={i}><td style={{...td2,fontWeight:700,color:P.purple}}>{r.analyte}<div style={{fontWeight:500,color:P.muted,fontSize:11}}>{r.label}</div></td><td style={{...td2,color:P.muted}}>{r.unit??"—"}</td><td style={td2}>{r.normalLow} – {r.normalHigh}</td><td style={{...td2,color:!r.criticalLowUnbounded?P.red:P.muted}}>{!r.criticalLowUnbounded?`< ${r.criticalLow}`:"—"}</td><td style={{...td2,color:!r.criticalHighUnbounded?P.red:P.muted}}>{!r.criticalHighUnbounded?`> ${r.criticalHigh}`:"—"}</td><td style={{...td2,color:P.muted}}>{r.stratum??"adulto"}</td><td style={{...td2,color:P.muted,fontSize:11}}>{r.source??"—"}</td></tr>)}</tbody></table></div></div>;
      }
      return <div/>;
     })()
    ):(
    <div style={{display:"grid",gridTemplateColumns:"250px 1fr 1fr",gap:16,marginTop:16,alignItems:"start"}} className="mos-res3">
     <div style={{...card2,padding:16}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:15,fontWeight:700}}>Filtros</span><span style={link} {...act(()=>{setResQ("");setResTypeF("Todos");setResEstadoF("Todos");})}>Limpiar</span></div>
      <div style={{display:"flex",alignItems:"center",gap:8,border:`1px solid ${LINE}`,borderRadius:9,padding:"8px 11px",margin:"12px 0"}}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={P.muted} strokeWidth="1.9" aria-hidden><circle cx="11" cy="11" r="7"/><path d="M21 21l-4-4"/></svg><input value={resQ} onChange={e=>setResQ(e.target.value)} placeholder="Buscar por estudio o paciente…" style={{border:0,outline:"none",fontSize:12.5,width:"100%",fontFamily:UI,background:"transparent",color:P.ink}}/></div>
      <div style={flbl}>Tipo de estudio</div><select value={resTypeF} onChange={e=>setResTypeF(e.target.value)} style={selSty}><option>Todos</option><option>Laboratorio</option><option>Imagenología</option></select>
      <div style={flbl}>Estado</div><select value={resEstadoF} onChange={e=>setResEstadoF(e.target.value)} style={selSty}><option>Todos</option><option>Hallazgos</option><option>Normal</option><option>En seguimiento</option><option>En revisión</option></select>
      <div style={{marginTop:14,fontSize:12,color:P.muted}}>{filteredItems.length} de {allItems.length} resultado(s)</div>
     </div>
     <div style={{...card2,padding:8}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 10px"}}><span style={{fontSize:16,fontWeight:700}}>Resultados ({filteredItems.length})</span></div>
      {filteredItems.map(it=>{const[bg,fg]=rb(it.estado);const on=selItem?.resultId===it.resultId;const ico=it.tipo==="Imagenología"?"img":"flask";return <div key={it.resultId} {...act(()=>setResSel(it.resultId))} style={{display:"flex",alignItems:"center",gap:11,padding:11,borderRadius:11,cursor:"pointer",border:on?"1px solid #E0DAFB":"1px solid transparent",background:on?"#F6F5FE":"transparent"}}><span style={{width:36,height:36,borderRadius:9,background:"#EEEBFD",color:P.purple,display:"grid",placeItems:"center",flex:"0 0 auto"}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden><path d={ricoPath[ico]??ricoPath.flask}/></svg></span><div style={{flex:1,minWidth:0}}><div style={{fontWeight:700,fontSize:13.5}}>{it.analyte}</div><div style={{fontSize:11.5,color:P.muted}}>{it.patientName} · {fmtResD(it.receivedAt)}</div></div>{pill(bg,fg,it.estado)}</div>;})}
      {filteredItems.length===0&&(!resLoaded?<div aria-hidden>{Array.from({length:5}).map((_,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:11,padding:11}}><Skeleton w={36} h={36} r={9}/><div style={{flex:1}}><Skeleton w={"55%"} h={13}/><Skeleton w={"75%"} h={11} style={{marginTop:5}}/></div><Skeleton w={56} h={18} r={999}/></div>)}</div>:<div style={{padding:"30px 10px",textAlign:"center",color:P.muted,fontSize:13}}>{allItems.length===0?"Sin resultados registrados. Usa «+ Registrar resultado».":"Ningún resultado coincide con los filtros."}</div>)}
      {filteredItems.length>0&&<div style={{padding:"12px 10px",fontSize:12.5,color:P.muted}}>Mostrando {filteredItems.length} de {allItems.length} resultado(s)</div>}
     </div>
     <div style={{...card2,padding:18}} className="mos-detail">
      {selItem?(()=>{const[bg,fg]=rb(selItem.estado);const rng=labReferenceRanges().find(a=>a.analyte===selItem.analyte);const vColor=selItem.critical?P.red:selItem.estado==="Normal"?P.greenOnPale:P.amber;const critical=selItem.critical;return <>
      <div style={{display:"flex",gap:11}}><span style={{width:44,height:44,borderRadius:11,background:"#EEEBFD",color:P.purple,display:"grid",placeItems:"center",flex:"0 0 auto"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden><path d={ricoPath[selItem.tipo==="Imagenología"?"img":"flask"]??ricoPath.flask}/></svg></span><div style={{minWidth:0}}><div style={{fontSize:16,fontWeight:800,display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}>{selItem.analyte} {pill(bg,fg,selItem.estado)}</div><div style={{fontWeight:700,fontSize:14}}>{selItem.patientName}</div><div style={{fontSize:12.5,color:P.muted}}>{selItem.tipo} · {fmtResD(selItem.receivedAt)}</div></div></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,margin:"14px 0 4px"}}>
       <div style={{border:`1px solid ${LINE}`,borderRadius:10,padding:10}}><div style={{fontSize:18,fontWeight:800,color:vColor}}>{selItem.value}</div><div style={{fontSize:10.5,color:P.muted}}>Valor</div></div>
       <div style={{border:`1px solid ${LINE}`,borderRadius:10,padding:10}}><div style={{fontSize:14,fontWeight:800}}>{rng?`${rng.normalLow} – ${rng.normalHigh}`:"—"}</div><div style={{fontSize:10.5,color:P.muted}}>Rango normal</div></div>
       <div style={{border:`1px solid ${LINE}`,borderRadius:10,padding:10}}><div style={{fontSize:14,fontWeight:800,color:critical?P.red:P.ink}}>{critical?"Crítico":selItem.estado==="Normal"?"En rango":"Anormal"}</div><div style={{fontSize:10.5,color:P.muted}}>Clasificación CDS</div></div>
      </div>
      {rng&&<div style={{fontSize:11.5,color:P.muted,marginBottom:6}}>Límites de pánico (los mismos que marcan CRÍTICO): {rng.criticalLowUnbounded?"sin umbral bajo":`< ${rng.criticalLow}`} / {rng.criticalHighUnbounded?"sin umbral alto":`> ${rng.criticalHigh}`}</div>}
      <div style={{fontSize:14,fontWeight:700,margin:"12px 0 6px"}}>Interpretación</div>
      <div style={{background:critical?"#FDECEE":"#F3F7FF",border:`1px solid ${critical?"#F6CDD3":"#D3E2F7"}`,borderRadius:11,padding:"11px 13px",fontSize:12.5,display:"flex",gap:8,color:critical?"#9c1f34":"#1c3c66"}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden style={{flexShrink:0,marginTop:1}}><circle cx="12" cy="12" r="9"/><path d="M12 8v4M12 16h.01"/></svg><span>{selItem.interpretation||"Sin interpretación registrada."} <span style={{opacity:.7}}>(Interpretación determinista · sin IA generativa)</span></span></div>
      <div style={{fontSize:14,fontWeight:700,margin:"14px 0 6px"}}>Ciclo de vida</div>
      <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{["RECEIVED","VERIFIED","ACTIONED","CLOSED"].map(ls=>{const active=selItem.lifecycle===ls;const LBL:Record<string,string>={RECEIVED:"Recibido",VERIFIED:"Verificado",ACTIONED:"Accionado",CLOSED:"Cerrado"};return <span key={ls} style={{fontSize:11,fontWeight:700,borderRadius:999,padding:"3px 10px",background:active?P.purple:"#F0F1F6",color:active?"#fff":P.muted}}>{LBL[ls]}</span>;})}</div>
      <button onClick={()=>{setResTab("seguimiento");}} style={{marginTop:16,width:"100%",border:`1px solid ${LINE}`,background:P.white,borderRadius:10,padding:"10px",fontWeight:600,fontSize:13,cursor:"pointer",fontFamily:UI}}>Ver panel de seguimiento →</button>
      </>;})():<div style={{padding:"48px 20px",textAlign:"center",color:P.muted}}><div style={{fontSize:14,fontWeight:600,marginBottom:6}}>Sin resultado seleccionado</div><div style={{fontSize:12.5}}>{allItems.length===0?"Registra un resultado con «+ Registrar resultado».":"Elige un resultado de la lista para ver su detalle."}</div></div>}
     </div>
    </div>)}
   </div>;
  
}
