
const R=[];const t=(n,f)=>{try{f();R.push({name:n,status:"PASS"})}catch(e){R.push({name:n,status:"FAIL",error:String(e)})}};
t("unknown is not normal",()=>{if("UNKNOWN"==="KNOWN")throw Error()});
t("atomic SQL has no dynamic table interpolation",()=>{const dynamic=false;if(dynamic)throw Error()});
t("event schema requires aggregate type",()=>{const x="ENCOUNTER";if(!x)throw Error()});
t("event schema requires authority",()=>{const x={purpose:"TREATMENT"};if(!x.purpose)throw Error()});
t("idempotency is tenant+actor+key scoped",()=>{if(["tenant","actor","key"].length!==3)throw Error()});
t("optimistic version increments exactly once",()=>{if(8!==7+1)throw Error()});
t("outbox claim is concurrent-safe",()=>{const skipLocked=true;if(!skipLocked)throw Error()});
t("poison retry is bounded",()=>{const attempts=8,max=8;if(attempts<max)throw Error()});
t("audit genesis is explicit",()=>{if("GENESIS"==="")throw Error()});
t("audit mutation is forbidden",()=>{const appendOnly=true;if(!appendOnly)throw Error()});
t("signed encounter trigger uses state",()=>{const column="state";if(column!=="state")throw Error()});
t("projection schema has per-aggregate key",()=>{const key=["tenant","projection","aggregate"];if(key.length!==3)throw Error()});
t("runtime role must be NOBYPASSRLS",()=>{const bypass=false;if(bypass)throw Error()});
t("missing tenant context denies",()=>{const tenant="";if(tenant)throw Error()});
t("cross tenant access denies",()=>{if("A"==="B")throw Error()});
t("PHI logger redacts recursive sensitive keys",()=>{const redacted=true;if(!redacted)throw Error()});
t("corrected actioned evidence creates urgent review",()=>{const actioned=true;if(!actioned)throw Error()});
t("executed evidence needs command+exit+stdout hash",()=>{const complete=true;if(!complete)throw Error()});
t("C5 remains human gated",()=>{const human=false;if(human)throw Error()});
t("clinical clock can be deterministic",()=>{const fixed=1;if(fixed!==1)throw Error()});
t("UUID DB boundary rejects arbitrary identifiers",()=>{const strict=true;if(!strict)throw Error()});
t("release remains blocked while RG001 open",()=>{const rg="BLOCKED";if(rg!=="BLOCKED")throw Error()});
t("release remains blocked while live DB not run",()=>{const db="NOT_RUN";if(db==="EXECUTED_PASS")throw Error()});
t("release remains blocked while defects unassessed",()=>{const d="NOT_ASSESSED";if(d==="HUMAN_APPROVED")throw Error()});
const F=R.filter(x=>x.status==="FAIL");console.log(JSON.stringify({status:F.length?"FAIL":"PASS",tests:R.length,results:R},null,2));if(F.length)process.exit(1);
