export type ErrorClass="VALIDATION"|"AUTHENTICATION"|"AUTHORIZATION"|"CONFLICT"|"SAFETY_BLOCK"|"DEPENDENCY"|"INTERNAL";
export function httpStatus(c:ErrorClass){return({VALIDATION:400,AUTHENTICATION:401,AUTHORIZATION:403,CONFLICT:409,SAFETY_BLOCK:422,DEPENDENCY:503,INTERNAL:500} as const)[c];}
