import type{Sql,TransactionSql}from"postgres";import crypto from"node:crypto";import{canonicalize}from"../../canonical-json/src";import{assertTenantContext,type TenantContext}from"../../tenant-context/src";
export type ClinicalCommand=Readonly<{commandId:string;idempotencyKey:string;aggregateId:string;aggregateType:string;expectedVersion:number;eventId:string;eventType:string;payload:unknown;outboxId:string;topic:string;auditId:string;correlationId:string;occurredAt:string}>;
export async function executeAtomicClinicalCommand(sql:Sql,ctx:TenantContext,c:ClinicalCommand){assertTenantContext(ctx);return sql.begin(async(tx:TransactionSql)=>{
 await tx`select set_config('app.tenant_id',${ctx.tenantId},true),set_config('app.actor_id',${ctx.actorId},true),set_config('app.purpose',${ctx.purpose},true),set_config('app.request_id',${ctx.requestId},true)`;
 const h=crypto.createHash("sha256").update(canonicalize(c)).digest("hex");
 const claim=await tx`insert into command_idempotency(tenant_id,actor_id,key,request_hash,status,expires_at) values(${ctx.tenantId},${ctx.actorId},${c.idempotencyKey},${h},'IN_PROGRESS',now()+interval '24 hours') on conflict do nothing returning key`;
 if(!claim.length){const p=await tx`select request_hash,status,response_json from command_idempotency where tenant_id=${ctx.tenantId} and actor_id=${ctx.actorId} and key=${c.idempotencyKey} for update`;if(p[0]?.request_hash!==h)throw Error('IDEMPOTENCY_CONFLICT');if(p[0]?.status==='COMPLETED')return{replayed:true,response:p[0].response_json};throw Error('IDEMPOTENCY_IN_PROGRESS');}
 const v=await tx`insert into aggregate_versions(tenant_id,aggregate_id,version) values(${ctx.tenantId},${c.aggregateId},1) on conflict(tenant_id,aggregate_id) do update set version=aggregate_versions.version+1,updated_at=now() where aggregate_versions.version=${c.expectedVersion} returning version`;
 if(v.length!==1||Number(v[0]?.version)!==c.expectedVersion+1)throw Error('CONCURRENCY_CONFLICT');
 await tx`insert into clinical_events(id,tenant_id,aggregate_id,aggregate_type,sequence,actor_id,actor_type,authority,correlation_id,payload,schema_version,occurred_at) values(${c.eventId},${ctx.tenantId},${c.aggregateId},${c.aggregateType},${c.expectedVersion+1},${ctx.actorId},${ctx.actorType},${tx.json({purpose:ctx.purpose})},${c.correlationId},${tx.json(c.payload as never)},1,${c.occurredAt})`;
 await tx`insert into outbox(id,tenant_id,topic,aggregate_id,payload,state,available_at) values(${c.outboxId},${ctx.tenantId},${c.topic},${c.aggregateId},${tx.json({eventId:c.eventId} as never)},'PENDING',now())`;
 const audit=await tx`select app.append_audit_v17(${ctx.tenantId},${c.auditId},${ctx.actorId},'CLINICAL_COMMAND',${c.aggregateType},${tx.json({commandId:c.commandId,eventId:c.eventId} as never)}) as entry_hash`;
 const response={aggregateId:c.aggregateId,version:c.expectedVersion+1,eventId:c.eventId,outboxId:c.outboxId,auditId:c.auditId,auditHash:audit[0]?.entry_hash};
 await tx`update command_idempotency set status='COMPLETED',response_json=${tx.json(response)} where tenant_id=${ctx.tenantId} and actor_id=${ctx.actorId} and key=${c.idempotencyKey}`;return{replayed:false,response};});}
